### ISSUE TITLE
GmshGenerator::exe: Gmsh executable not found in given directory.

### ISSUE THREAD

**Issue by Batmanabcdefg** [c3m-labs/GmshLink#3]
Hello,
I cannot run the test benchmark in MMA12!
**error: GmshGenerator::exe: Gmsh executable not found in given directory.**

Gmsh folder routine should be correct!`
$GmshDirectory = "C:/Users/david/gmsh-4.3.0-Windows64/Gmsh.exe"`

**Comment by PintarM** [comment]
Hi OVGULIU,

Thank you for showing interest in our package. I think that the problem is that, you have to set path to directory containing the executable, not to executable itself (e.g. `$GmshDirectory = "C:/Users/david/gmsh-4.3.0-Windows64`). 
I have also pushed update to README and Examples.nb to emphasize this instructions.

**Comment by Batmanabcdefg** [comment]
Hi PintarM

I have found a new error due to the tests:``` (MMA 12 & GMSH 4.4.1 )

ToElementMesh::femtemnbb: 
   The bounds for BooleanRegion[(#1 || #2 || #3 || #4) && !#5 & , 
                                          4         9         3
     {Ball[{0, 0, 0}, 1], Ball[{1, 0, 0}, -], Ball[{-, 0, 0}, -], 
                                          5         5         5
            12         2
      Ball[{--, 0, 0}, -], Cuboid[{-2, -2, 0}, {5, 2, 2}]}] are 
            5          5
    {{-Infinity, Infinity}, {-Infinity, Infinity}, {-Infinity, Infinity}}
    . Unless finite numeric bounds are specified, the mesh generation will
     constrain the region to have finite bounds.

Set::shape: Lists {ImportMesh`Private`Gmsh`head, 
     ImportMesh`Private`Gmsh`order, ImportMesh`Private`Gmsh`noNodes, 
     ImportMesh`Private`Gmsh`reordering} and $Failed are not the same shape.

Part::pkspec1: The expression ImportMesh`Private`Gmsh`reordering
     cannot be used as a part specification.

Part::pkspec1: The expression ImportMesh`Private`Gmsh`reordering
     cannot be used as a part specification.
```

**Comment by PintarM** [comment]
Hi!
Unfortunately I cannot reproduce the error that you get (with the same software versions). Was this message produced by the first example in "Examples.nb" notebook? You can also try specifying explicit region bounds, if that maybe helps (see below).

```mathematica
bounds = RegionBounds[reg]

mesh = ToElementMesh[
  reg,
  bounds,
  "BoundaryMeshGenerator" -> None,
  "ElementMeshGenerator" -> GmshGenerator
]
```

**Comment by PintarM** [comment]
Hi  @OVGULIU,
Did my suggestion above solve your issues?
